shop/config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :products
  resources :suppliers
  resources :orders
  resources :consumers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

shop/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

shop/app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order_item, only: %i[ show edit update destroy ]

  # GET /order_items or /order_items.json
  def index
    @order_items = OrderItem.all
  end

  # GET /order_items/1 or /order_items/1.json
  def show
  end

  # GET /order_items/new
  def new
    @order_item = OrderItem.new
  end

  # GET /order_items/1/edit
  def edit
  end

  # POST /order_items or /order_items.json
  def create
    @order_item = OrderItem.new(order_item_params)

    respond_to do |format|
      if @order_item.save
        format.html { redirect_to @order_item, notice: "Order item was successfully created." }
        format.json { render :show, status: :created, location: @order_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_items/1 or /order_items/1.json
  def update
    respond_to do |format|
      if @order_item.update(order_item_params)
        format.html { redirect_to @order_item, notice: "Order item was successfully updated." }
        format.json { render :show, status: :ok, location: @order_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1 or /order_items/1.json
  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_url, notice: "Order item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_item_params
      params.require(:order_item).permit(:count, :worth, :order_id, :product_id)
    end
end

shop/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

shop/app/views/order_items/_form.html.erb
<%= form_with(model: order_item, local: true) do |form| %>
  <% if order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="field">
    <%= form.label :worth %>
    <%= form.text_field :worth %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

shop/app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

shop/app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Count</th>
      <th>Worth</th>
      <th>Order</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.count %></td>
        <td><%= order_item.worth %></td>
        <td><%= order_item.order %></td>
        <td><%= order_item.product %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Item', new_order_item_path %>

shop/app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Back', order_items_path %>

shop/app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Count:</strong>
  <%= @order_item.count %>
</p>

<p>
  <strong>Worth:</strong>
  <%= @order_item.worth %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order_item.product %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>